"""Add discount model and user fields

Revision ID: 3a24a69b0686
Revises: c410c48cc0ab
Create Date: 2025-06-19 17:43:11.198686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a24a69b0686'
down_revision = 'c410c48cc0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('discounts', sa.Column('discount_type', sa.Enum('FIXED', 'PERCENTAGE', name='discounttype'), nullable=False))
    op.add_column('discounts', sa.Column('valid_from', sa.Date(), nullable=True))
    op.add_column('discounts', sa.Column('valid_to', sa.Date(), nullable=True))
    op.add_column('discounts', sa.Column('target_city', sa.String(), nullable=True))
    op.add_column('discounts', sa.Column('required_client_status', sa.Enum('REGULAR', 'SILVER', 'GOLD', 'PLATINUM', name='clientstatus'), nullable=True))
    op.add_column('discounts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('discounts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('discounts', 'value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_discounts_target_city'), 'discounts', ['target_city'], unique=False)
    op.drop_column('discounts', 'conditions')
    op.drop_column('discounts', 'type')
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'status')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', name='userstatus'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'date_of_birth')
    op.add_column('discounts', sa.Column('type', postgresql.ENUM('FIXED', 'PERCENTAGE', name='discounttype'), autoincrement=False, nullable=False))
    op.add_column('discounts', sa.Column('conditions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_discounts_target_city'), table_name='discounts')
    op.alter_column('discounts', 'value',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('discounts', 'updated_at')
    op.drop_column('discounts', 'created_at')
    op.drop_column('discounts', 'required_client_status')
    op.drop_column('discounts', 'target_city')
    op.drop_column('discounts', 'valid_to')
    op.drop_column('discounts', 'valid_from')
    op.drop_column('discounts', 'discount_type')
    op.drop_column('discounts', 'description')
    # ### end Alembic commands ### 