"""Add discount fields to booking

Revision ID: a311d3d89f16
Revises: 3a24a69b0686
Create Date: 2025-06-19 17:44:11.257065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a311d3d89f16'
down_revision = '3a24a69b0686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('applied_discount_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'bookings', 'discounts', ['applied_discount_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'discount_amount')
    op.drop_column('bookings', 'applied_discount_id')
    # ### end Alembic commands ### 