"""Add missing columns to tours table

Revision ID: a63992c0c01a
Revises: 001
Create Date: 2025-06-18 19:57:36.428262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a63992c0c01a'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('tourists_count', sa.Integer(), nullable=False))
    op.alter_column('bookings', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='status::text::integer')
    op.drop_column('bookings', 'participants_count')
    op.drop_column('bookings', 'booking_date')
    op.add_column('tours', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('tours', sa.Column('country', sa.String(length=255), nullable=False))
    op.add_column('tours', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('tours', sa.Column('base_price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('tours', sa.Column('max_tourists', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('available_count', sa.Integer(), nullable=False))
    op.add_column('tours', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tours', 'hotels', ['hotel_id'], ['id'])
    op.drop_column('tours', 'max_participants')
    op.drop_column('tours', 'destination')
    op.drop_column('tours', 'price')
    op.drop_column('tours', 'title')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('CLIENT', 'AGENCY_MANAGER', 'OPERATOR_MANAGER', 'ADMIN', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BLOCKED', 'PENDING', name='userstatus'), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'phone')
    op.add_column('tours', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tours', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('tours', sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('tours', sa.Column('max_participants', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tours', type_='foreignkey')
    op.drop_column('tours', 'hotel_id')
    op.drop_column('tours', 'available_count')
    op.drop_column('tours', 'max_tourists')
    op.drop_column('tours', 'base_price')
    op.drop_column('tours', 'city')
    op.drop_column('tours', 'country')
    op.drop_column('tours', 'name')
    op.add_column('bookings', sa.Column('booking_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('participants_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('bookings', 'status',
               existing_type=sa.Integer(),
               type_=postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'),
               existing_nullable=True)
    op.alter_column('bookings', 'total_price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('bookings', 'tourists_count')
    # ### end Alembic commands ### 