"""Add fields for multi-step booking

Revision ID: c410c48cc0ab
Revises: 72b276ce0572
Create Date: 2025-06-19 17:34:34.652653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c410c48cc0ab'
down_revision = '72b276ce0572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('hotel_tier', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('tourists_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bookings', sa.Column('booker_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bookings', sa.Column('extra_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'extra_services')
    op.drop_column('bookings', 'booker_info')
    op.drop_column('bookings', 'tourists_data')
    op.drop_column('bookings', 'hotel_tier')
    # ### end Alembic commands ### 